import Vue from 'vue';

import './styles/quasar.styl';
import '@quasar/extras/roboto-font/roboto-font.css';
import '@quasar/extras/material-icons/material-icons.css';
import {
  QSpace,
  Quasar,
  QLayout,
  QHeader,
  QDrawer,
  QPageContainer,
  QPage,
  QToolbar,
  QToolbarTitle,
  QBtn,
  QIcon,
  QList,
  QInput,
  QItem,
  QItemSection,
  QItemLabel,
  QTabs,
  QTab,
  QRouteTab,
  QParallax,
  QStepper,
  QStep,
  QStepperNavigation,
  QTimeline,
  QTimelineEntry,
  QCard,
  QCardSection,
  QCardActions,
  QCarousel,
  QCarouselControl,
  QCarouselSlide,
} from 'quasar';

Vue.use(Quasar, {
  config: {},
  components: {
    QSpace,
    QLayout,
    QHeader,
    QDrawer,
    QPageContainer,
    QPage,
    QToolbar,
    QToolbarTitle,
    QBtn,
    QIcon,
    QList,
    QInput,
    QItem,
    QItemSection,
    QItemLabel,
    QTabs,
    QTab,
    QRouteTab,
    QParallax,
    QStepper,
    QStep,
    QStepperNavigation,
    QTimeline,
    QTimelineEntry,
    QCard,
    QCardSection,
    QCardActions,
    QCarousel,
    QCarouselControl,
    QCarouselSlide,
  },
  directives: {
  },
  plugins: {
  },
});
